/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  IdropDownData,
  IdropDownOption,
} from './models/index';
import {
  EventEmitter,
} from '@stencil/core';


export namespace Components {

  interface AsMsDdl {
    'data': Array<IdropDownData>;
    'options': IdropDownOption;
  }
  interface AsMsDdlAttributes extends StencilHTMLAttributes {
    'data'?: Array<IdropDownData>;
    'onSelectedValues'?: (event: CustomEvent<Array<any>>) => void;
    'options'?: IdropDownOption;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AsMsDdl': Components.AsMsDdl;
  }

  interface StencilIntrinsicElements {
    'as-ms-ddl': Components.AsMsDdlAttributes;
  }


  interface HTMLAsMsDdlElement extends Components.AsMsDdl, HTMLStencilElement {}
  var HTMLAsMsDdlElement: {
    prototype: HTMLAsMsDdlElement;
    new (): HTMLAsMsDdlElement;
  };

  interface HTMLElementTagNameMap {
    'as-ms-ddl': HTMLAsMsDdlElement
  }

  interface ElementTagNameMap {
    'as-ms-ddl': HTMLAsMsDdlElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
